# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'playground' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for playground
  pod 'React', :path => '../../node_modules/react-native', :subspecs => [
  'Core',
  'CxxBridge',
  'DevSupport', # Include this to enable In-App Devmenu if RN >= 0.43
  'RCTAnimation',
  'RCTActionSheet',
  'RCTText',
  'RCTLinkingIOS',
  'RCTPushNotification',
  'RCTImage',
  'RCTSettings',
  'RCTVibration',
  'RCTNetwork',
  'RCTWebSocket', # needed for debugging
  # Add any other subspecs you want to use in your project
  ]
  # Explicitly include Yoga if you are using RN >= 0.42.0
  pod 'ProgressHUD', :path => '../../'
  pod 'yoga', :path => '../../node_modules/react-native/ReactCommon/yoga'
  pod 'DoubleConversion', :podspec => '../../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  # pod 'GLog', :podspec => '../../node_modules/react-native/third-party-podspecs/GLog.podspec'
  pod 'glog', :podspec => '../../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../../node_modules/react-native/third-party-podspecs/Folly.podspec'

end
